/**
 * Dicionário de nomes de exibição para logos.
 * Usa o nome do arquivo (lowercase) como chave.
 * Fallback: deriveNameFromLogo
 */
export const logoDisplayNames: Record<string, string> = {
	"99pay.png": "99Pay",
	"abank.png": "Akbank",
	"abcbrasil.png": "ABC Brasil",
	"abnamro.png": "ABN AMRO",
	"abrapetite.png": "Abrapetite",
	"absolutbank.png": "Absolut Bank",
	"acessobank.png": "Acesso Bank",
	"activo.bank.png": "ActivoBank",
	"activtrades.png": "ActivTrades",
	"agbank.png": "Agricultural Bank of China",
	"agibank.png": "AgiBank",
	"agora.png": "Ágora Investimentos",
	"agribank.png": "BIDV",
	"aktia.png": "Aktia Bank",
	"alelo.png": "Alelo",
	"alfabank.png": "Alfa-Bank",
	"alphabank.png": "Alpha Bank",
	"alt.bank.png": "alt.bank",
	"amazon.png": "Amazon",
	"amazonia.png": "Banco da Amazônia",
	"ame.png": "Amex",
	"ameriprisefinancial.png": "Ameriprise Financial",
	"amex.png": "Amex",
	"amppersonalbanking.png": "AMP",
	"anz.png": "ANZ",
	"asaas.png": "Asaas",
	"asn.png": "ASN Bank",
	"astro-pay.png": "AstroPay",
	"atlantico.png": "ATLANTICO",
	"atticabank.png": "Attica Bank",
	"aura.png": "Aura",
	"avenida.png": "Lojas Avenida",
	"avenuesecuritie.png": "Avenue",
	"azul.png": "Azul",
	"b3.png": "B3",
	"bahamas-cred.png": "Bahamas Cred",
	"bancamediolanum.png": "Banca Mediolanum",
	"bancamps.png": "Banca Monte dei Paschi di Siena",
	"bancaopopularedisondrio.png": "Banca Populare di Sondrio",
	"banco-bai.png": "Banco Bai",
	"banco-bic.png": "Banco BIC",
	"bancobpm.png": "Banco BPM",
	"banco-comercio-industria.png": "Banco de Comércio e Indústria",
	"bancodavivienda.png": "Davivienda",
	"bancodebogota.png": "Banco de Bogotá",
	"bancodelbajio.png": "BanBajío",
	"bancodeoccident.png": "Banco de Occident",
	"bancohipotecario.png": "Banco Hipotecario",
	"bancolombia.png": "Bancolombia",
	"bancomacro.png": "Banco Macro",
	"banconacion.png": "Banco Nación",
	"banco-parana.png": "Paraná Banco",
	"bancopatagonia.png": "Banco Patagonia",
	"bancoposta.png": "BancoPosta",
	"banco-poupanca-credito.png": "Banco de Poupança e Crédito",
	"banese.png": "Banco Banese",
	"banestes.png": "Banestes",
	"bangkokbank.png": "Bangkok Bank",
	"banif.png": "Banif",
	"bankia.png": "Bankia",
	"bankmandiri.png": "Bank Mandiri",
	"banknorwegian.png": "Bank Norwegian",
	"bankofaland.png": "Bank of Åland",
	"bankofamerica.png": "Bank of America",
	"bankofchina.png": "Bank of China",
	"bankrakyat.png": "Bank Rakyat",
	"bankwest.png": "Bankwest",
	"banorte.png": "Banorte",
	"banpara.png": "Banpará",
	"banrisul.png": "Banrisul",
	"bari.png": "Banco Bari",
	"bb.png": "Banco do Brasil",
	"bbva.png": "BBVA",
	"bca.png": "BCA",
	"bemol.png": "Bemol",
	"bendigobank.png": "Bendigo Bank",
	"benvisavale.png": "Ben Visa Vale",
	"betfair.png": "Betfair",
	"bidv.png": "BIDV",
	"bilhete-unico.png": "Bilhete Único",
	"binance.png": "Binance",
	"binomo.png": "Binomo",
	"bipa.png": "Bipa",
	"bitybank.png": "BityBank",
	"bitz.png": "Bitz",
	"bmg.png": "BMG",
	"bmg-corinthians.png": "BMG Corinthians",
	"bmo.png": "BMO",
	"bni.png": "BNI",
	"bnl.png": "BNL",
	"bnpparibas.png": "BNP Paribas",
	"boq.png": "BOQ",
	"bperbanca.png": "BPER Banca",
	"bpi.png": "BPI",
	"bradesco.png": "Bradesco",
	"bradesco-empresas.png": "Bradesco Empresas",
	"bradesco-prime.png": "Bradesco Prime",
	"brasilcard.png": "BrasilCard",
	"brb.png": "Banco BRB",
	"brde.png": "BRDE",
	"bs2.png": "Banco BS2",
	"btg.empresas.png": "BTG Empresas",
	"btgpactual.png": "BTG Pactual",
	"btgplus.png": "BTG Plus",
	"buddy.bank.png": "Buddy Bank",
	"bunq.png": "Bunq",
	"bv.png": "Banco BV",
	"c6bank.png": "C6 Bank",
	"c-a.png": "C&A",
	"cacique.png": "Banco Cacique",
	"caisse.png": "Caisse",
	"caixa.png": "Caixa",
	"caixabank.png": "CaixaBank",
	"caixageral.png": "Caixa Geral de Depósitos",
	"caju.png": "Caju",
	"c-a-pay.png": "C&A Pay",
	"capitalone.png": "Capital One",
	"carrefour.png": "Carrefour",
	"cassadepositieprestiti.png": "Cassa Depositi e Prestiti",
	"cdb.png": "CDB",
	"cdp.png": "CDP",
	"celcoin.png": "Celcoin",
	"cetelem.png": "Cetelem",
	"charlesschwab.png": "Charles Schwab",
	"chinaconstructionbank.png": "China Construction Bank",
	"cibc.png": "CIBC",
	"cimbbank.png": "CIMB Bank",
	"cimbniaga.png": "CIMB Niaga",
	"citibank.png": "Citibank",
	"clara.png": "Clara",
	"clear.png": "Clear",
	"clear-corretora.png": "Clear Corretora",
	"coinbase.png": "Coinbase",
	"commbank.png": "CommBank",
	"commerzbank.png": "Commerzbank",
	"conectcar.png": "ConectCar",
	"contabilizei.bank.png": "Contabilizei Bank",
	"contasimples.png": "Conta Simples",
	"cooperativa-ailos.png": "Cooperativa Ailos",
	"cooperativa-cresol.png": "Cooperativa Cresol",
	"cooperativa-unilos.png": "Cooperativa Unilos",
	"coopercard.png": "Coopercard",
	"cooperforte.png": "Cooperforte",
	"cora.png": "Cora",
	"credicard.png": "Credicard",
	"credicard-on.png": "Credicard On",
	"credicard-zero.png": "Credicard Zero",
	"credisis.png": "Credisis",
	"creditagricole.png": "Credit Agricole",
	"creditagricoleitaly.png": "Credit Agricole Italy",
	"creditas.png": "Creditas",
	"creditbankofmoscow.png": "Credit Bank of Moscow",
	"creditdunord.png": "Credit du Nord",
	"credito.agricola.png": "Crédito Agrícola",
	"creditoemiliano.png": "Credito Emiliano",
	"crefisa.png": "Crefisa",
	"cruzeirodosul.png": "Cruzeiro do Sul",
	"crypto-com.png": "Crypto.com",
	"ctt.png": "CTT",
	"danskebank.png": "Danske Bank",
	"daycoval.png": "Daycoval",
	"desjardins.png": "Desjardins",
	"digio.png": "Digio",
	"digiplus.png": "Digiplus",
	"diin.png": "Diin",
	"diners.png": "Diners",
	"dinheiro.png": "Dinheiro",
	"dmcard.png": "DM Card",
	"dnbbank.png": "DNB Bank",
	"dotz.png": "Dotz",
	"dzbank.png": "DZ Bank",
	"easynvest.png": "EasyInvest",
	"ebanxgo.png": "EBANX Go",
	"edenred.png": "Edenred",
	"efi.bank.png": "EFI Bank",
	"elliot.png": "Elliot",
	"elo.png": "Elo",
	"eqi.png": "EQI",
	"eurobank.png": "Eurobank",
	"evlibank.png": "Evli Bank",
	"exodus.png": "Exodus",
	"fidelity.png": "Fidelity",
	"flash.png": "Flash",
	"forexbank.png": "Forex Bank",
	"fortbrasil.png": "Fort Brasil",
	"foxbit.png": "Foxbit",
	"freedom.24.png": "Freedom 24",
	"garantibank.png": "Garantibank",
	"gazprombank.png": "Gazprombank",
	"genial.png": "Genial",
	"grao.png": "Grão",
	"handelsbanken.png": "Handelsbanken",
	"havan.png": "Havan",
	"hipercard.png": "Hipercard",
	"hongleong.png": "Hong Leong",
	"hotmart.png": "Hotmart",
	"hsbc.png": "HSBC",
	"hypovereinsbank.png": "Hypo Vereinsbank",
	"icatu.png": "Icatu",
	"icbc.png": "ICBC",
	"iccreabanca.png": "ICCREA Banca",
	"ifood-beneficios.png": "iFood Benefícios",
	"ifood-conta-digital.png": "iFood Conta Digital",
	"inbursa.png": "Inbursa",
	"infinitepay.png": "InfinitePay",
	"ing.png": "ING",
	"intermedium.png": "Inter",
	"interpj.png": "Inter PJ",
	"intesa-san-paolo.png": "Intesa Sanpaolo",
	"ion.png": "Ion",
	"iqoption.png": "IQ Option",
	"isbank.png": "Isbank",
	"itau.png": "Itaú",
	"itau-ion.png": "Itaú Ion",
	"itaupersonnalite.png": "Itaú Personnalité",
	"itau-uniclass.png": "Itaú Uniclass",
	"iti.png": "Iti",
	"jpbank.png": "JP Bank",
	"jpmorgan.png": "JPMorgan",
	"juno.png": "Juno",
	"jyskebank.png": "Jyske Bank",
	"kbank.png": "KBank",
	"kbkookminbank.png": "KB Kookmin Bank",
	"kdbbank.png": "KDB Bank",
	"kebhanabank.png": "KEB Hana Bank",
	"kfw.png": "KFW",
	"kiwify.png": "Kiwify",
	"klarna.png": "Klarna",
	"krungthaibank.png": "Krungthai Bank",
	"latam.pass.png": "Latam Pass",
	"lhv.png": "LHV",
	"lojasamericanas.png": "Lojas Americanas",
	"macquariebank.png": "Macquarie Bank",
	"magalu-pay.png": "Magalu Pay",
	"magnetis.png": "Magnetis",
	"mais.png": "Mais",
	"mandiri.png": "Mandiri",
	"marisa.png": "Marisa",
	"master-black.png": "Master Black",
	"mastercard.png": "Mastercard",
	"maybank.png": "Maybank",
	"mediobanca.png": "Mediobanca",
	"meliuz.png": "Méliuz",
	"mercadobitcoin.png": "Mercado Bitcoin",
	"mercadolivre.png": "Mercado Livre",
	"mercadopago.png": "Mercado Pago",
	"mercadopagocartao.png": "Mercado Pago Cartão",
	"mercantilbrasil.png": "Banco Mercantil",
	"meu-util.png": "Meu Útil",
	"midway.png": "Midway",
	"milleniumbcp.png": "Millenium BCP",
	"mizuhobank.png": "Mizuho Bank",
	"modalmais.png": "Modal Mais",
	"moey.png": "Moey",
	"moip.png": "Moip",
	"monetizze.png": "Monetizze",
	"monetus.png": "Monetus",
	"monzo-bank.png": "Monzo Bank",
	"morganstanley.png": "Morgan Stanley",
	"mps.png": "MPS",
	"mufgbank.png": "MUFG Bank",
	"n26.png": "N26",
	"nab.png": "NAB",
	"national.australia.bank.png": "National Australia Bank",
	"nationalbank.png": "National Bank",
	"neon.png": "Neon",
	"next.png": "Next",
	"nhbank.png": "NH Bank",
	"nochubank.png": "Nochu Bank",
	"noh.png": "NOH",
	"nomad.png": "Nomad",
	"nordea.png": "Nordea",
	"nordeste.png": "Nordeste",
	"nordnet.png": "Nordnet",
	"novadax.png": "Novadax",
	"novafatura.png": "Nova Fatura",
	"novobancopt.png": "Novo Banco PT",
	"novucard.png": "Novu Card",
	"nubank.pj.png": "Nubank PJ",
	"nubank.png": "Nubank",
	"nubank-ultravioleta.png": "Nubank Ultravioleta",
	"nuconta.png": "Nu Conta",
	"nu-invest.png": "Nu Invest",
	"nykredit.png": "Nykredit",
	"olymp.trade.png": "Olymp Trade",
	"omni.png": "Omni",
	"opbank.png": "OP Bank",
	"orama.png": "Orama",
	"original.png": "Banco Original",
	"otkritie.png": "Otkritie",
	"pag.png": "Pag",
	"pagar-me.png": "Pagar.me",
	"pagbank.png": "PagBank",
	"pagseguro.png": "PagSeguro",
	"pan.png": "Pan",
	"pao-acucar.png": "Pão de Açúcar",
	"passfolio.png": "Passfolio",
	"payoneer.png": "Payoneer",
	"paypal.png": "PayPal",
	"payu.png": "PayU",
	"petrobras.png": "Petrobras",
	"picpay.png": "PicPay",
	"piraeusbank.png": "Piraeus Bank",
	"pix.png": "Pix",
	"players-bank.png": "Players Bank",
	"pluxxe.png": "Pluxxe",
	"pncfinancialservices.png": "PNC Financial Services",
	"pocket.option.png": "Pocket Option",
	"portoseguro.png": "Porto Seguro",
	"primacredi.png": "Primacredi",
	"proencamercado.png": "Proença Supermercados",
	"promsvyazbank.png": "Promsvyazbank",
	"publicbank.png": "Public Bank",
	"quotex.png": "Quotex",
	"rabobank.png": "Rabobank",
	"raiffeisenbank.png": "Raiffeisen Bank",
	"rappi-bank.png": "Rappi Bank",
	"rbcroyalbank.png": "RBC Royal Bank",
	"rbs.png": "RBS",
	"rci.png": "RCI",
	"recargapay.png": "RecargaPay",
	"renner.png": "Renner",
	"revolut.png": "Revolut",
	"rhbbank.png": "RHB Bank",
	"riachuelo.png": "Riachuelo",
	"rico.png": "Rico",
	"sabadell.png": "Sabadell",
	"safra.png": "Safra",
	"samsung.png": "Samsung",
	"santander.png": "Santander",
	"santander-private.png": "Santander Private",
	"saraiva.png": "Saraiva",
	"sberbank.png": "Sberbank",
	"scb.png": "SCB",
	"scotiabank.png": "Scotiabank",
	"sebbank.png": "SEB Bank",
	"sem-parar.png": "Sem Parar",
	"senff.png": "Senff",
	"serasa-consumidor.png": "Serasa Consumidor",
	"shinhanbank.png": "Shinhan Bank",
	"shopee.png": "Shopee",
	"shoptime.png": "Shoptime",
	"sicoob.png": "Sicoob",
	"sicredi.png": "Sicredi",
	"sisprime.png": "Sisprime",
	"smbc.png": "SMBC",
	"smiles.png": "Smiles",
	"smpbank.png": "SMP Bank",
	"snsbank.png": "SNS Bank",
	"socialbank.png": "Social Bank",
	"societegenerale.png": "Banco Societe Generale",
	"sodexo.png": "Sodexo",
	"sofi.png": "Sofi",
	"sofisadireto.png": "Sofisa Direto",
	"sparebank1.png": "SpareBank 1",
	"sportingbet.png": "Sportingbet",
	"spuerkeess.png": "Spuerkeess",
	"standardchartered.png": "Standard Chartered",
	"stanford-federal-credit-union.png": "Stanford Federal Credit Union",
	"stone.png": "Stone",
	"storebrandbank.png": "Storebrand Bank",
	"submarino.png": "Submarino",
	"sumup.png": "Sumup",
	"suncorpbank.png": "Suncorp Bank",
	"superdigital.png": "Super Digital",
	"swedbank.png": "Swedbank",
	"swile.png": "Swile",
	"sydbank.png": "SYD Bank",
	"tangerine.png": "Tangerine",
	"tdameritrade.png": "TD Ameritrade",
	"tdbank.png": "TD Bank",
	"techcombank.png": "Techcombank",
	"telekom.png": "Telekom",
	"tesourodireto.png": "Tesouro Direto",
	"tesouronacional.png": "Tesouro Nacional",
	"ticket.png": "Ticket",
	"tinkoff.png": "Tinkoff",
	"tmbbank.png": "TMB Bank",
	"ton.png": "Ton",
	"toroinvestimentos.png": "Toro Investimentos",
	"trade.republic.png": "Trade Republic",
	"trading.212.png": "Trading 212",
	"transferwise.png": "TransferWise",
	"tribanco.png": "Tribanco",
	"trigg.png": "Trigg",
	"tudoazul.png": "Tudo Azul",
	"uber.drive.png": "Uber Drive",
	"ubibanca.png": "Ubi Banca",
	"unicred.png": "Unicred",
	"unicreditbank.png": "UniCredit Bank",
	"unimed.seguros.png": "Unimed Seguros",
	"unipolbanca.png": "Unipol Banca",
	"uniprime.png": "Uniprime",
	"up.brasil.png": "Up Brasil",
	"urbeme.png": "Urbeme",
	"urpay.png": "UrPay",
	"usbank.png": "U.S. Bank",
	"veloe.png": "Veloe",
	"venmo.png": "Venmo",
	"verocard.png": "Verocard",
	"viacredi.png": "Viacredi",
	"vietcombank.png": "Vietcombank",
	"vietinbank.png": "VietinBank",
	"visa.png": "Visa",
	"vitreo.png": "Vitreo",
	"votorantim.png": "Votorantim",
	"vr.png": "VR",
	"vtbbank.png": "VTB Bank",
	"vuon.png": "Vuon",
	"warren.png": "Warren",
	"wellsfargo.png": "Wells Fargo",
	"westpac.png": "Westpac",
	"wiipo.png": "Wiipo",
	"will-bank.png": "Will Bank",
	"wirecard.png": "Wirecard",
	"wise.png": "Wise",
	"woop.png": "Woop",
	"xdex.png": "XDEX",
	"xm.png": "XM",
	"xp.png": "XP Investimentos",
	"xtb.png": "XTB",
	"yapikredi.png": "Yapi Kredi",
	"z1.png": "Z1",
	"zilch.png": "Zilch",
	"ziraatbank.png": "Ziraat Bank",
	"zro-bank.png": "ZRO Bank",
};
